### ISSUE TITLE
Possibility for embedding code inside the templates

### ISSUE THREAD

**Issue by saravanak** [mrak/stubby4node#47]
I would like to generate sequence of steps that are derivations of an index value. Eg:

```
Content-Range:  <% calc_content_range(url[0]) %>
```

As we are using `ejs` templates, AND because this is a node project, we can instruct stubby to pre-load some javascript files and then we can execute the ejs template . 

I see that the code `endpoints.js::applyCaptures` method explicitly replaces `<%..%>` with `<=..=>`. 
I think that including the functionality of arbitrary code execution within the template will be awesome.

**Comment by mrak** [comment]
It was a design decision from stubby's onset to not do this. Since stubby is meant to be a cross-language specification per se, we do not aim to add code interpretation in the templates.

The use of `ejs` is coincidental implementation detail, as this interpolation format for regex captures could easily be implemented across languages.

Sorry
